name: fire_app
description: Aplikasi deteksi kebakaran
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.5.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.4
  curved_navigation_bar: ^1.0.3
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  http: ^0.13.4
  location: ^4.3.0
  lottie: ^1.2.1
  maps_launcher: ^2.0.1
  shared_preferences: ^2.0.12
  timeago: ^3.2.1

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "Fire App"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/fonts/
    - assets/lottie/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
