name: CI/CD

on:
  push:
    branches: [beta]

jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: KAnggara/fireapp
          token: ${{ secrets.GH_TOKEN }}
      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --depth=10000
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: "5.8.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
      - name: Create version.txt with NuGetVersionV2
        run: echo ${{ steps.gitversion.outputs.NuGetVersionV2  }} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt
  build:
    name: Build APK and Create release
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion
      - name: Read version & build key
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
      - run: ls
      - run: cat version.txt
      - run: ls -l android
      - run: echo ${{ secrets.JKS }} > android/key.jks
      - run: echo ${{ secrets.KEY }} > android/key.properties
      - run: ls -l
      - run: ls -l android
      - run: cat android/key.properties
